server:
  port: 9901

eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:xiaostudy.test@localhost:9900/eureka/

spring:
  application:
    name: server-service
  cloud:
    loadbalancer:
      retry:
        enabled: false